name: Run Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  php-tests:
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    strategy:
      matrix:
        php: [8.2]
        laravel: [10.*]
        stability: [prefer-stable]
        os: [ubuntu-latest]
        exclude:
          - php: 8.0
            laravel: 10.*
          - php: 8.3
            laravel: 9.*

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Update apt sources
        run: |
          sudo apt-get check || sudo apt --fix-broken install -y
          sudo apt-get update

      - name: Install French Locale
        run: sudo apt-get install language-pack-fr

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Install dependencies
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: |
            composer require "illuminate/contracts:${{ matrix.laravel }}" --dev --no-interaction --no-update
            composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: List Installed Dependencies
        run: composer show -D

      - name: Execute tests with Supercharge
        run: vendor/bin/supercharge phpunit
        env:
          SUPERCHARGE_TOKEN: ${{ secrets.SUPERCHARGE_TOKEN }}

      - name: Execute tests locally
        run: vendor/bin/phpunit
